### ISSUE TITLE
Enable JSON access log to allow streaming it to a remote log service

### ISSUE THREAD

**Issue by kitsunet** [flownative/docker-nginx#17]
Respective lines are already in place 

https://github.com/flownative/docker-nginx/blob/main/root-files/opt/flownative/nginx/etc/nginx.conf.template#L69

Not sure we need the buffer?

We would need to move `/opt/flownative/log` to a shared volume though to make it accessible for logging service containers.

**Comment by robertlemke** [comment]
JSON-support is included in https://github.com/flownative/docker-nginx/pull/18
